name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v6
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: Apply automatic formatting

  tests:
    name: Tests
    needs: formatting
    runs-on: 'ubuntu-24.04'
    env:
      DUMMYPROJECTPATH: './test-dummy'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.65.0
          frozen: true
          cache: true
          activate-environment: true
      - run: |
            copier copy ./ "${DUMMYPROJECTPATH}" \
              -l \
              -d description="Dummy project to test the template." \
              -d projectname="testdummy" \
              -d max_python="3.13" \
              -d min_python="3.12" \
              -d nightly_deps=""
      - run: git init  # ``setuptools`` complains if it is not a git repository.
        working-directory: ${{ env.DUMMYPROJECTPATH }}
      - run: sed -i '/dependencies = \[/a\    "numpy"' pyproject.toml
        working-directory: ${{ env.DUMMYPROJECTPATH }}
      - run: pixi install --frozen --locked --all
        working-directory: ${{ env.DUMMYPROJECTPATH }}
      - run: pixi run test
        working-directory: ${{ env.DUMMYPROJECTPATH }}
      - run: pixi run docs
        working-directory: ${{ env.DUMMYPROJECTPATH }}
      - run: git add -A && pixi run lint  # Files should be added to be checked
        working-directory: ${{ env.DUMMYPROJECTPATH }}

